---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 19847.
--- DateTime: 2026/6/26 11:57
---

-- scripts/like.lua
-- KEYS[1] = like:{targetType}:{targetId}
-- KEYS[2] = like:count:{targetType}
-- KEYS[3] = user:like:{userId}
-- KEYS[4] = ranking:{type}
-- ARGV[1] = userId
-- ARGV[2] = targetId
-- ARGV[3] = action: 'like' or 'unlike'

local setKey = KEYS[1]
local countKey = KEYS[2]
local userKey = KEYS[3]
local rankingKey = KEYS[4]
local userId = ARGV[1]
local targetId = ARGV[2]
local action = ARGV[3]

if action == 'like' then
    -- 检查是否已点赞
    if redis.call('sismember', setKey, userId) == 1 then
        return -1  -- 已点赞
    end
    -- 添加到点赞集合
    redis.call('sadd', setKey, userId)
    -- 添加到用户点赞列表
    redis.call('sadd', userKey, targetId)
    -- 增加计数
    redis.call('hincrby', countKey, targetId, 1)
    -- 更新排行榜
    redis.call('zincrby', rankingKey, 1, targetId)
    return 1
else
    -- 取消点赞
    if redis.call('sismember', setKey, userId) == 0 then
        return -2  -- 未点赞
    end
    redis.call('srem', setKey, userId)
    redis.call('srem', userKey, targetId)
    redis.call('hincrby', countKey, targetId, -1)
    redis.call('zincrby', rankingKey, -1, targetId)
    return 1
end